### PR TITLE
Add category button

### PR DESCRIPTION
**Pull request by LordRekishi**

### CODE REVIEW

**Comment by LordRekishi** [comment]
[End of quiz page (Basic version)](https://trello.com/c/93EUDDek/71-end-of-quiz-page-basic-version)

**Comment by LordRekishi** [comment]
[Add choose category button and functionality to end of quiz](https://trello.com/c/aScGyREW/133-add-choose-category-button-and-functionality-to-end-of-quiz)

**Comment by LordRekishi** [comment]
> I'll wait with resolving the conflict until the review is complete as the conflict will be affected by the review.

I can fix it later if you don't have time

**Comment by ErikssonF** [comment]
> 

I have time, but if we want to implement the changes I mentioned then it will affect the conflict, so I'll sort that out when we've decided.

**Pull request merged**
