### PR TITLE
Bug fix 01: Progress bar & Quiz reset

### PR DESCRIPTION
**Pull request by LordRekishi**
This will fix the quiz not resetting when exiting out of the quiz mid-question. This also adds resetting of quiz when exiting result page, and the ability to exit mid quiz and start over with the same words.

### CODE REVIEW

**Comment by LordRekishi** [comment]
[Bug fix: When choosing an answer, not clicking next question, going back to landing page and then starting the quiz again](https://trello.com/c/XOMPCLT3/162-bug-fix-when-choosing-an-answer-not-clicking-next-question-going-back-to-landing-page-and-then-starting-the-quiz-again)

**Comment by LordRekishi** [comment]
Added checks that language and/or category is the same as originally chosen, if not the quiz will restart with new words.

**Comment by LordRekishi** [comment]
[Bug Fix 01: Change language/category in middle of quiz will not reset balls](https://trello.com/c/6A3hGYhb/166-bug-fix-01-change-language-category-in-middle-of-quiz-will-not-reset-balls)

**Comment by LordRekishi** [comment]
[Bug fix 01: When choosing an answer, not clicking next question, going back to landing page and then starting the quiz again](https://trello.com/c/XOMPCLT3/162-bug-fix-01-when-choosing-an-answer-not-clicking-next-question-going-back-to-landing-page-and-then-starting-the-quiz-again)

**Comment by helenahalldiniths** [comment]
What the quiz shows is now correct, however I don't think that the functionallity works as intended. The answers are not reset which leads to incorrect results. Example when I'm stating with a fruit quiz, exits mid section and then starts with an animal quiz.
Skärmavbild 2022-10-21 kl  10 07 49

**Review by helenahalldiniths — CHANGES_REQUESTED** [review]
Doesn't work as intended. More info in my comment

**Comment by LordRekishi** [comment]
> What the quiz shows is now correct, however I don't think that the functionallity works as intended. The answers are not reset which leads to incorrect results. Example when I'm stating with a fruit quiz, exits mid section and then starts with an animal quiz.
> 
> As shown below all "your answer" are read from the "fruit" table and not the "animal" one. I ended the fruit quiz after 3 questions but all my answers look like they are from the fruit table. Skärmavbild 2022-10-21 kl 10 07 49

This is part of another bug that has been identified and not something this fix is trying to solve. Please see this task -> [Bug fix: Result table (on Trello board)](https://trello.com/c/patW5R0f)

**Review by helenahalldiniths — APPROVED** [review]
Ok! Then it is fine. I merge main and fixed conflicts

**Pull request merged**
